
   - name: install mysql server
     ansible.builtin.package:
      name: mysql-server
      state: present


   - name: start and enable the server
     ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes



   - name: install pymysql
     ansible.builtin.pip:
      name: PyMySQL
      executable: pip3.9
   - name: set mysql root password
     community.mysql.mysql_user:
      name: root
      host: '%'
      password: RoboShop@1
      login_unix_socket: /var/lib/mysql/mysql.sock
      check_implicit_admin: true
      priv: "*.*:ALL,GRANT"
      state: present
  #  - name: set mysql root password
  #    community.mysql.mysql_user:
  #     name: root
  #     host: localhost
  #     password: RoboShop@1
  #     login_unix_socket: /var/lib/mysql/mysql.sock
  #     check_implicit_admin: true
  #     state: present